routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

app/Http/Controllers/User/AuthController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Order;
use App\Models\Province;
use App\Models\User;
use App\Models\UserVerify;
use App\Mail\WelcomeMail;
use App\Mail\ResetMail;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Hash;

class AuthController extends Controller
{
    public function __construct()
    {
        $this->middleware('guest')->except('profile', 'edit_profile', 'update_profile', 'do_logout');
    }
    public function index()
    {
        return view('page.user.auth.main');
    }
    public function do_login(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'email' => 'required|email|max:255',
            'password' => 'required|min:8',
        ]);

        if ($validator->fails()) {
            $errors = $validator->errors();
            if ($errors->has('email')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('email'),
                ]);
            } else {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('password'),
                ]);
            }
        }
        $check = User::where("email", "=", $request->email)->first();
        if ($check) {
            if ($check->email_verified_at) {
                if (Auth::guard('web')->attempt(['email' => $request->email, 'password' => $request->password, 'role' => 'Customer'], $request->remember)) {
                    if(Auth::guard('web')->user()->province_id){
                        return response()->json([
                            'alert' => 'success',
                            'message' => 'Welcome back ' . Auth::guard('web')->user()->name, 
                        ]);
                    }else{
                        return response()->json([
                            'alert' => 'success',
                            'message' => 'Welcome back ' . Auth::guard('web')->user()->name . '. Harap lengkapi profile anda', 
                        ]);
                    }
                } else {
                    return response()->json([
                        'alert' => 'error',
                        'message' => 'Maaf, sepertinya ada beberapa kesalahan yang terdeteksi, silakan coba lagi.',
                    ]);
                }
            } else {
                return response()->json([
                    'alert' => 'error',
                    'message' => 'Harap Verifikasi di gmail terlebih dahulu.',
                ]);
            }
        }
    }
    public function do_register(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required',
            'email' => 'required|unique:users|max:255',
            'phone' => 'required|unique:users|min:9|max:15',
            'password' => 'required|min:8|max:12',
        ]);

        if ($validator->fails()) {
            $errors = $validator->errors();
            if ($errors->has('name')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('name'),
                ]);
            } elseif ($errors->has('email')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('email'),
                ]);
            } elseif ($errors->has('phone')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('phone'),
                ]);
            } elseif ($errors->has('password')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('password'),
                ]);
            }
        }
        $user = new User;
        $user->name = Str::title($request->name);
        $user->email = $request->email;
        $user->phone = $request->phone;
        $user->username = Str::before($request->email, '@');
        $user->password = Hash::make($request->password);
        $user->role = 'Customer';
        $user->save();

        $token = Str::random(64);

        UserVerify::create([
            'user_id' => $user->id,
            'token' => $token
        ]);
        Mail::to($request->email)->send(new WelcomeMail($user, $token));
        return response()->json([
            'alert' => 'success',
            'message' => 'Customer ' . $request->name . ' Registered',
        ]);
    }
    public function verify($token)
    {
        $verifyUser = UserVerify::where('token', $token)->first();

        $message = 'Sorry your email cannot be identified.';

        if (!is_null($verifyUser)) {
            $user = $verifyUser->user;

            if (!$user->email_verified_at) {
                $verifyUser->user->email_verified_at = date("Y-m-d H:i:s");
                $verifyUser->user->save();
                $message = "Your e-mail is verified. You can now login.";
            } else {
                $message = "Your e-mail is already verified. You can now login.";
            }
        }

        return redirect()->route('user.auth.index')->with('message', $message);
    }
    public function do_forgot(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'email' => 'required|email|exists:users',
        ]);
        if ($validator->fails()) {
            $errors = $validator->errors();
            if ($errors->has('email')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('email'),
                ]);
            }
        }

        $token = Str::random(64);

        DB::table('password_resets')->insert([
            'email' => $request->email,
            'token' => $token,
            'created_at' => Carbon::now()
        ]);
        Mail::to($request->email)->send(new ResetMail($token));
        return response()->json([
            'alert' => 'success',
            'message' => 'We have e-mailed your password reset link!',
        ]);
    }
    public function reset($token)
    {
        return view('page.user.auth.reset', compact('token'));
    }
    public function do_reset(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'token' => 'required|exists:password_resets',
            'password' => 'required|string|min:6|confirmed',
            'password_confirmation' => 'required'
        ]);
        if ($validator->fails()) {
            $errors = $validator->errors();
            if ($errors->has('token')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('token'),
                ]);
            } elseif ($errors->has('password')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('password'),
                ]);
            } elseif ($errors->has('password_confirmation')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('password_confirmation'),
                ]);
            }
        }

        $updatePassword = DB::table('password_resets')
            ->where([
                'token' => $request->token
            ])
            ->first();

        if (!$updatePassword) {
            return response()->json([
                'alert' => 'error',
                'message' => 'Invalid token!',
            ]);
        }
        $user = User::where('email', $updatePassword->email)
            ->update(['password' => Hash::make($request->password)]);

        DB::table('password_resets')->where(['email' => $updatePassword->email])->delete();
        return response()->json([
            'alert' => 'success',
            'message' => 'Your password has been changed!',
            'callback' => 'auth',
        ]);
    }
    public function profile(Request $request)
    {
        if ($request->ajax()) {
            $token = Auth::user()->id;
            $keywords = $request->keywords;
            $collection = Order::where('user_id', $token)
                ->orderBy('id', 'DESC')
                ->paginate(10);
            return view('page.user.auth.list', compact('collection'));
        }
        return view('page.user.auth.profile');
    }
    public function edit_profile(User $user)
    {
        $provinsi= Province::get();
        return view('page.user.auth.edit', compact('user','provinsi'));
    }
    public function update_profile(Request $request, User $user)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required',
            'email' => 'required|max:255',
            'phone' => 'required|min:9|max:15',
            'address' => 'required',
            'province' => 'required',
            'city' => 'required',
            'subdistrict' => 'required',
            'photo' => 'required',
        ]);
        if ($validator->fails()) {
            $errors = $validator->errors();
            if ($errors->has('name')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('name'),
                ]);
            } elseif ($errors->has('email')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('email'),
                ]);
            } elseif ($errors->has('phone')) {
                return response()->json([

app/Http/Controllers/User/CartController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use App\Models\Cart;
use App\Models\User;
use App\Models\Product;
use App\Models\Province;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\DB;

class CartController extends Controller
{
    public function index(Request $request)
    {
        $user = User::where('id', Auth::user()->id)->first();
        $provinsi= Province::get();
        $token = Auth::user()->id;
        $collection = Cart::where('user_id', $token)
            ->get();
        return view('page.user.checkout.main', compact('collection','provinsi','user'));
    }
    public function list(Request $request)
    {
        $output = '';
        $total_harga = 0;
        $token = Auth::user()->id;
        $collection = Cart::where('user_id', $token)->get();
        foreach ($collection as $data_load) {
            $price = "price_" . $data_load->type;
            $stock = "stock_" . $data_load->type;
            $total_harga += $data_load->product->$price * $data_load->qty;
            $output .= '
                <div class="top-cart-item">
                    <div class="top-cart-item-image">
                        <a href="' . route('user.product.show', $data_load->product->slug) . '">
                        <img src="' . $data_load->product->image . '" alt="' . $data_load->product->titles . '" /></a>
                    </div>
                    <div class="top-cart-item-desc">
                        <div class="top-cart-item-desc-title">
                            <a href="' . route('user.product.show', $data_load->product->slug) . '">' . $data_load->product->titles . ' | ' . Str::title($data_load->type) . '</a>
                            <span class="top-cart-item-price d-block">
                            ' . number_format($data_load->product->$price) . '
                            </span>
                        </div>
                        <div class="top-cart-item-quantity">
                            ' . number_format($data_load->qty) . '
                            <br>
                            <a onclick="handle_delete(`' . route('user.cart.destroy', $data_load->id) . '`);"><i class="icon-trash2"></i></a>
                        </div>
                    </div>
                </div>
            ';
        }
        return response()->json([
            'collection' => $output,
            'total_harga' => $total_harga,
            'total_item' => $collection->count(),
        ]);
    }
    public function store(Request $request)
    {
        $token = Auth::user()->id;
        $validator = Validator::make($request->all(), [
            'quantity' => 'required',
            'size' => 'required',
        ]);
        if ($validator->fails()) {
            $errors = $validator->errors();
            if ($errors->has('quantity')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('quantity'),
                ]);
            } elseif ($errors->has('size')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('size'),
                ]);
            }
        }
        $stock = Product::where('id', $request->product)->first();
        $stocknya = 'stock_' . $request->size;
        if ($stock->$stocknya >= $request->quantity) {
            $check = Cart::where('product_id', $request->product)
                ->where('user_id', $token)
                ->where('type', $request->size)
                ->first();
            if ($check) {
                DB::select(DB::raw("
                update carts set qty = qty+$request->quantity, updated_at = '" . date('Y-m-d H:i:s') . "' where id = '$check->id'
                "));
            } else {
                $cart = new Cart;
                $cart->user_id = $token;
                $cart->product_id = $request->product;
                $cart->type = $request->size;
                $cart->qty = $request->quantity;
                $cart->save();
            }
            return response()->json([
                'alert' => 'success',
                'message' => 'Added to cart',
            ]);
        } else {
            return response()->json([
                'alert' => 'info',
                'message' => 'Stock Produk tidak cukup',
            ]);
        }
    }
    public function destroy(Cart $cart)
    {
        $cart->delete();
        return response()->json([
            'alert' => 'success',
            'message' => 'Cart ' . $cart->product->titles . ' Deleted',
        ]);
    }
}

app/Http/Controllers/User/CategoryController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Category;
use App\Models\Product;

class CategoryController extends Controller
{
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $keywords = $request->keywords;
            $collection = Category::where('titles','like','%'.$keywords.'%')
            ->paginate(10);
            return view('page.user.category.list', compact('collection'));
        }
        return view('page.user.category.main');
    }
    public function show(Request $request, Category $category)
    {
        if ($request->ajax()) {
            $keywords = $request->keywords;
            $collection = Product::where('categories_id','=',$category->id)
            ->where('titles','like','%'.$keywords.'%')
            ->paginate(10);
            return view('page.user.category.show_list', compact('collection'));
        }
        return view('page.user.category.show',compact('category'));
    }
}

app/Http/Controllers/User/CityController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Models\City;
use Illuminate\Http\Request;

class CityController extends Controller
{
    public function list(Request $request)
    {
        $result = City::where('province_id','=',$request->param)->get();
        echo json_encode($result);
    }
    public function get_list(Request $request)
    {
        $result = City::where('province_id','=',$request->id_province)->get();
        $list = "<option>Pilih Kota</option>";
        foreach($result as $row){
            $list.="<option value='$row->city_id'>$row->city_name</option>";
        }
        echo $list;
    }
}

app/Http/Controllers/User/ProvinceController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Province;

class ProvinceController extends Controller
{
    public function list(Request $request)
    {
        $result = Province::get();
        echo json_encode($result);
    }
}

app/View/Components/UserLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class UserLayout extends Component
{
    public $title;
    public function __construct($title)
    {
        $this->title = $title;
    }
    public function render()
    {
        return view('theme.user.main');
    }
}

resources/views/page/user/home/about.blade.php
<x-user-layout title="About">
    <section id="content">
        <div class="content-wrap">
            <div class="container clearfix">
                <div class="row">
                    <div class="col-md-3">
                        <div class="card">
                            <div class="card-body bg-warning">
                                <i class="icon-instagram" style="font-size:2rem;"></i>
                                <span> rvs_id</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="card">
                            <div class="card-body bg-warning">
                                <i class="icon-whatsapp-square" style="font-size:2rem;"></i>
                                <span>
                                    0821 - 1233 - 7831
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="card">
                            <div class="card-body bg-warning">
                                <i class="icon-map-marker1" style="font-size:2rem;"></i>
                                <span style="font-size:0.975em;">
                                    Jl. babakan sentral no 79 rw 05 rt 05 kelurahan sukapura kecamatan kiaracondong
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</x-user-layout>

resources/views/page/user/home/main.blade.php
<x-user-layout title="Home">
    <section id="content">
        <div class="content-wrap">
            <div class="container clearfix">
                <h2>{!!$inspiring!!}</h2>
                <h2 class="text-align: center">New Product</h2>
                <hr>
                <br>
                <div class="row gutter-40 col-mb-80">
                    <!-- Post Content
                    ============================================= -->
                    <div class="postcontent col-lg-12 order-lg-last">

                        <!-- Shop
                        ============================================= -->
                        <div id="shop" class="shop row grid-container gutter-20" data-layout="fitRows">
                            @php
                            $product = \App\Models\Product::orderBy("id","desc")->limit(6)->get();
                            @endphp
                            @foreach ($product as $item)
                            <div class="product col-md-4 col-sm-6 {{$item->category->slug}}">
                                <div class="grid-inner">
                                    <div class="product-image">
                                        <a href="#"><img src="{{$item->image}}" alt="{{$item->titles}}"></a>
                                        <a href="#"><img src="{{$item->image}}" alt="{{$item->titles}}"></a>
                                        {{-- <div class="sale-flash badge bg-secondary p-2">Out of Stock</div> --}}
                                        <div class="bg-overlay">
                                            <div class="bg-overlay-content align-items-end justify-content-between" data-hover-animate="fadeIn" data-hover-speed="400">
                                                <a href="{{route('user.product.show',$item->slug)}}" class="btn btn-dark me-2"><i class="icon-shopping-cart"></i></a>
                                                {{-- <a href="include/ajax/shop-item.html" class="btn btn-dark" data-lightbox="ajax"><i class="icon-line-expand"></i></a> --}}
                                            </div>
                                            <div class="bg-overlay-bg bg-transparent"></div>
                                        </div>
                                    </div>
                                    <div class="product-desc">
                                        <center>
                                            <div class="product-title">
                                                <h3><a href="#">{{$item->titles}}</a></h3>
                                            </div>
                                        </center>
                                        <center>
                                            <div class="product-price">
                                                <ins id="default_price">
                                                    @if($item->price_s == $item->price_xxl)
                                                    Rp. {{number_format($item->price_s)}}
                                                    @else
                                                    Rp. {{number_format($item->price_s)}} - Rp. {{number_format($item->price_xxl)}}
                                                    @endif
                                                </ins>
                                            </div>
                                        </center>
                                    </div>
                                </div>
                            </div>
                            @endforeach
                        </div><!-- #shop end -->

                    </div><!-- .postcontent end -->

                    <!-- Sidebar
                    ============================================= -->
                    <div class="d-none sidebar col-lg-3">
                        <div class="sidebar-widgets-wrap">

                            <div class="widget widget-filter-links">

                                <h4>Select Category</h4>
                                <ul class="custom-filter ps-2" data-container="#shop" data-active-class="active-filter">
                                    <li class="widget-filter-reset active-filter"><a href="#" data-filter="*">Clear</a></li>
                                    @php
                                    $kategori = \App\Models\Category::get();
                                    @endphp
                                    @foreach ($kategori as $item)
                                    <li><a href="#" data-filter=".{{$item->slug}}">{{$item->titles}}</a></li>
                                    @endforeach
                                </ul>

                            </div>


                            <div class="widget widget-filter-links d-none">

                                <h4>Sort By</h4>
                                <ul class="shop-sorting ps-2">
                                    <li class="widget-filter-reset active-filter"><a href="#" data-sort-by="original-order">Clear</a></li>
                                    <li><a href="#" data-sort-by="name">Name</a></li>
                                    <li><a href="#" data-sort-by="price_lh">Price: Low to High</a></li>
                                    <li><a href="#" data-sort-by="price_hl">Price: High to Low</a></li>
                                </ul>

                            </div>

                        </div>
                    </div><!-- .sidebar end -->
                </div>
                <hr>
                <div class="row align-items-stretch">

                    <div class="col-md-5 col-padding min-vh-75" style="background: url('{{asset('img/logo_admin.png')}}') center center no-repeat; background-size: cover;"></div>

                    <div class="col-md-7 col-padding">
                        <div>
                            <div class="heading-block">
                                <h3>{{config('app.name')}}</h3>
                            </div>
                            <div class="row col-mb-50">
                                <div class="col-lg-12">
                                    <p>Reveries di angkat dari kehidupan manusia yang setiap individunya memiliki watak, cerita & takdirnya masing - masing. namun sosial membuat standar yang harus diikuti agar manusia bisa dianggap "manusia".</p>
                                    <p>Sosial memaksa manusia untuk memenuhi standar sehingga menjadi hal yang biasa dan manusia kehilangan jati dirinya. maka dari itu, Reveries hadir untuk mendukung manusia agar bangga menjadi individu yang berbeda tanpa memandang usia ataupun gender</p>
                                </div>
                            </div>

                        </div>
                    </div>

                </div>

            </div>
        </div>
    </section>
    @section('custom_js')
    <script>
        jQuery(document).ready(function($) {
            $(window).on('pluginIsotopeReady', function() {
                // $('#shop').isotope({
                // 	transitionDuration: '0.65s',
                // 	getSortData: {
                // 		name: '.product-title',
                // 		price_lh: function( itemElem ) {
                // 			if( $(itemElem).find('.product-price').find('ins').length > 0 ) {
                // 				var price = $(itemElem).find('.product-price ins').text();
                // 			} else {
                // 				var price = $(itemElem).find('.product-price').text();
                // 			}

                // 			priceNum = price.split("$");

                // 			return parseFloat( priceNum[1] );
                // 		},
                // 		price_hl: function( itemElem ) {
                // 			if( $(itemElem).find('.product-price').find('ins').length > 0 ) {
                // 				var price = $(itemElem).find('.product-price ins').text();
                // 			} else {
                // 				var price = $(itemElem).find('.product-price').text();
                // 			}

                // 			priceNum = price.split("$");

                // 			return parseFloat( priceNum[1] );
                // 		}
                // 	},
                // 	sortAscending: {
                // 		name: true,
                // 		price_lh: true,
                // 		price_hl: false
                // 	}
                // });

                $('.custom-filter:not(.no-count)').children('li:not(.widget-filter-reset)').each(function() {
                    var element = $(this),
                        elementFilter = element.children('a').attr('data-filter'),
                        elementFilterContainer = element.parents('.custom-filter').attr('data-container');

                    elementFilterCount = Number(jQuery(elementFilterContainer).find(elementFilter).length);

                    element.append('<span>' + elementFilterCount + '</span>');

                });

                $('.shop-sorting li').click(function() {
                    $('.shop-sorting').find('li').removeClass('active-filter');
                    $(this).addClass('active-filter');
                    var sortByValue = $(this).find('a').attr('data-sort-by');
                    $('#shop').isotope({
                        sortBy: sortByValue
                    });
                    return false;
                });
            });
        });
    </script>
    @endsection
</x-user-layout>